import React, { useEffect } from "react";
import { useState } from "react";
import { Card, FormField, Loader } from "../components";

const { section, h1, p, loader, h2_render_card, h2_search_text, search_text } =
  {
    section: "max-w-7xl mx-auto",
    h1: "font-extrabold text-[#222328] text-[32px]",
    p: "mt-2 text-[#666e75] text-[14px] max-w-[500px]",
    loader: "flex justify-center items-center",
    h2_render_card: "mt-5 font-bold text-[#6469ff] text-xl uppercase",
    h2_search_text: "font-medium text-[#666e75] text-xl mb-3",
    search_text:
      "grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3",
  };

const RenderCard = ({ title, data }) => {
  if (data?.length > 0) {
    return data.map((post) => <Card key={post._id} {...post} />);
  }
  return <h2 className={h2_render_card}>{title}</h2>;
};

const Home = () => {
  const [loading, setLoading] = useState(false);
  const [allPosts, setAllPosts] = useState(null);
  const [searchText, setSearchText] = useState("");
  const [searchTimeout, setSearchTimeout] = useState(null);
  const [searchedResult, setSearchedResult] = useState(null);

  const fetchPosts = async () => {
    setLoading(true);

    try {
      const response = await fetch("http://localhost:8080/api/v1/post", {
        method: "GET",
        headers: {
          "Content-Type": "application/json",
        },
      });
      if (response.ok) {
        const result = await response.json();

        setAllPosts(result.data.reverse());
      }
    } catch (err) {
      alert(err);
    } finally {
      setLoading(false);
    }
  };

  const handleSearchChange = (e) => {
    clearTimeout(searchTimeout);
    setSearchText(e.target.value);

    setSearchTimeout(
      setTimeout(() => {
        const searchResult = allPosts.filter(
          (item) =>
            item.name.toLowerCase().includes(searchText.toLowerCase()) ||
            item.prompt.toLowerCase().includes(searchText.toLowerCase())
        );

        setSearchedResult(searchResult);
      }, 500)
    );
  };

  useEffect(() => {
    fetchPosts();
  }, []);

  return (
    <section className={section}>
      <div>
        <h1 className={h1}>The Community Showcase</h1>
        <p className={p}>
          Browse through a collection of imaginative and visually stunning
          images generated by Imagee
        </p>
      </div>
      <div className="mt-16">
        <FormField
          labelName="Search posts"
          type="text"
          name="text"
          placeholder="Search posts"
          value={searchText}
          handleChange={handleSearchChange}
        />
      </div>
      <div className="mt-10">
        {loading ? (
          <div className={loader}>
            <Loader />
          </div>
        ) : (
          <>
            {searchText && (
              <h2 className={h2_search_text}>
                Showing results for{" "}
                <span className="text-[#222328]">{searchText}</span>
              </h2>
            )}
            <div className={search_text}>
              {searchText ? (
                <RenderCard
                  data={searchedResult}
                  title="No search results found"
                />
              ) : (
                <RenderCard data={allPosts} title="No posts found" />
              )}
            </div>
          </>
        )}
      </div>
    </section>
  );
};

export default Home;
